name: StudioGraphene-Dependency-Analytics

on:
  push:
    branches: [dev]

jobs:
  call-worflow:
    uses: studiographene/github-action-workflows/.github/workflows/pulse-dependencies-analytics.yml@master # if you want alternatively pin to tag version version
    secrets: inherit