name: StudioGraphene-SAST-Analytics
on:
  push:
    branches: [master]
jobs:
  sast_analytics:
    uses: studiographene/github-action-workflows/.github/workflows/pulse-sast-analytics.yml@master
    secrets: inherit
    with:
      semgrep_options: --exclude-rule root.configs.semgrep.rules.eslint.detect-object-injection --exclude '**/__tests__/**' --exclude '**/*.test.ts' --exclude '**/*.spec.ts'
